import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const HomePage = () => {
  const { isAuthenticated } = useAuth();
  const ctaTarget = isAuthenticated ? '/dashboard' : '/register';
  const ctaLabel = isAuthenticated ? 'Go to Dashboard' : 'Get Started Free';

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-20 text-center">
      <h1 className="text-4xl font-bold text-slate-800 mb-4">Your Personal AI Fitness Coach</h1>
      <p className="text-slate-500 mb-8 text-lg">
        Get a personalized workout plan, diet suggestions, and weekly schedule generated by AI —
        tailored to your goals.
      </p>
      <Link to={ctaTarget} className="btn-primary text-base py-3 px-8 inline-block">
        {ctaLabel}
      </Link>
    </div>
  );
};

export default HomePage;
